### ISSUE TITLE
Error while running CIRIquant

### ISSUE THREAD

**Issue by nandakumaryellapu** [bioinfo-biols/CIRIquant#50]
Hi Iam trying to run CIRIquant using the following command
----------------------------------
CIRIquant -t 4 \
          -1 read1.fastq \
          -2 read2.fastq \
          --config config_file.yml \
          -o /panfs/pfs.local/work/biostat/nyellapu/Praveen/cRNA_Feb2023/trialrun/result \
          -p test

here is my configuration file looks like
----------------------------------------
tools:
  bwa: /home/nyellapu/.conda/envs/CIRI/bin/bwa
  hisat2: /home/nyellapu/.conda/envs/CIRI/bin/hisat2
  stringtie: /home/nyellapu/.conda/envs/CIRI/bin/stringtie
  samtools: /home/nyellapu/.conda/envs/CIRI/bin/samtools

reference:
  fasta: /panfs/pfs.local/work/biostat/nyellapu/reference/mouse_mm39/GCF_000001635.27_GRCm39_genomic.fa
  gtf: /panfs/pfs.local/work/biostat/nyellapu/reference/mouse_mm39/mouse_mm39.gtf
  bwa_index: /panfs/pfs.local/work/biostat/nyellapu/reference/mouse_mm39/bwa_index/bwa
  hisat_index: /panfs/pfs.local/work/biostat/nyellapu/reference/mouse_mm39/hisat_index/grcm38/genome

I am getting the following errors while running
--------------------------------------------------------

Traceback (most recent call last):
  File "/home/nyellapu/.conda/envs/CIRI/bin/CIRIquant", line 8, in <module>
    sys.exit(main())
  File "/home/nyellapu/.conda/envs/CIRI/lib/python2.7/site-packages/CIRIquant/main.py", line 89, in main
    config = check_config(check_file(args.config_file))
  File "/home/nyellapu/.conda/envs/CIRI/lib/python2.7/site-packages/CIRIquant/utils.py", line 109, in check_config
    return config['name']
KeyError: 'name'

Please help me to resolve this. Trying to hard to come out. ant understand why this error is happening

**Comment by Kevinzjy** [comment]
The key "name" and its value is missing in your configuration file. An example configuration is provided at https://ciri-cookbook.readthedocs.io/en/latest/CIRIquant_2_quantification.html

![image](https://user-images.githubusercontent.com/10627200/220952443-fced292e-020e-4387-b29f-f12f76b3354c.png)

**Comment by nandakumaryellapu** [comment]
Hi Thanks for the reply. I added the name and it ran successfully.
But I cant understand the result from the out put. the "text.gtf" file contains no proper data about the quantified reads.
would you please help me how to understand the result and extract the quantified reads. seems i got some errors too. I am attaching the entire result folder that contains the log file though. are you able to tell some thing from this?

[result.zip](https://github.com/bioinfo-biols/CIRIquant/files/10816356/result.zip)

**Comment by Kevinzjy** [comment]
Hi @nandakumaryellapu , please refer to the manual https://ciri-cookbook.readthedocs.io/en/latest/CIRIquant_2_quantification.html#output-format for detailed information about how to interprete the result. 

The attached log file says you are not using the correct hisat2 version:`
Warning: the current version of HISAT2 () is older than the version (2.0.2-beta) used to build the index.
         Users are strongly recommended to update HISAT2 to the latest version.
`
so please ensure the version of HISAT2 provided to CIRIquant is the same version used to build the index.

**Comment by nandakumaryellapu** [comment]
@Kevinzjy thanks for your important leads. I repeated the process using the hisat index from the same hisat2 used for the analysis.
I am attaching the log file over here (test1.log). Actually the result file generated test1.xlxs (test1.gtf) is not showing the following attributes.
<html>
<body>


rnaser_bsj | number of bsj reads in RNase R data (only when --RNaseR is specificed)
-- | --
rnaser_fsj | number of fsj reads in RNase R data (only when --RNaseR is specificed)
gene_id | ensemble id of host gene
gene_name | HGNC symbol of host gene
gene_type | type of host gene in gtf file


</body>
</html>

is my out put is correct? I can find the scores, but related to which circular-RNA? i cant find their names in the output.

[test1.log](https://github.com/bioinfo-biols/CIRIquant/files/10843227/test1.log)



[test1.xlsx](https://github.com/bioinfo-biols/CIRIquant/files/10843244/test1.xlsx)

**Comment by Kevinzjy** [comment]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/10627200/221730030-ba78c941-3b21-40e6-a3d7-4e249db6c9d9.png">

The "circ_id" in your output is the name of circRNAs.

**Comment by Kevinzjy** [comment]
Hi @nandakumaryellapu , it seems that you are using the wrong version of reference genome & gene annotation gtf. The reference genome and gtf should be downloaded from the same source (e.g. GENCODE or Ensembl), and the chromosome name should be exactly the same in these files.
